name = "hCRV"
uuid = "2d1db8c4-538f-4dd1-8a05-5f5f15e60ae8"
authors = ["claudiodelsole <claudiodelsi96@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CSV = "0.10.15"
DSP = "0.8.4"
DataFrames = "1.8.1"
Distributions = "0.25.120"
KernelDensity = "0.6.10"
MCMCDiagnosticTools = "0.3.15"
NPZ = "0.4.3"
Optim = "1.13.2"
Plots = "1.41.1"
Polynomials = "4.1.0"
QuadGK = "2.11.2"
Random = "1.11.0"
Roots = "2.2.10"
SpecialFunctions = "2.5.1"
